### ISSUE TITLE
Upgrade k3os

### ISSUE THREAD

**Issue by Tchoupinax** [sgielen/picl-k3os-image-generator#2]
Hello !

Thank you for your work, you made an awesome work. I have never suceeded to install native k3os image on my raspberry 4 (and according to this link https://github.com/rancher/k3os/issues/111 i am not alone) but with your project it works (and ssh config is good, it it what i was looking for !).

I would like to ask, how can i upgrade k3os version ? I tried to replace 0.6.0 by v0.9.0-rc5 which is the lastest release but i get a kernel panic. 

Can you upgrade or explain how you do it (if is is understandable :p)

Thank you,
Regards :)

**Comment by sgielen** [comment]
You should be able to safely upgrade the k3os system without upgrading the kernel. I think the command was `k3os-upgrade-rootfs` but I don't have a k3os installation booted currently to try it... Otherwise, you can probably also update the link to `k3os-rootfs-arm64.tar.gz` in `build-image.sh` to a newer version and rebuild the image.

If, after this, you are still having kernel panics, please do feel encouraged to reopen this issue and include some information on the panic you're seeing :)

**Comment by sgielen** [comment]
I could reproduce a kernel panic after the upgrade to 0.9.0 and have reported a new issue: #4.
