### ISSUE TITLE
Wireless interface not detected on Raspberry Pi 3 B+

### ISSUE THREAD

**Issue by Neonox31** [sgielen/picl-k3os-image-generator#6]
Hello and first thanks for this nice image builder 👍

I was able to build a k3os image for my rpi 3B+ but the wifi doesn't seem to be working.
I have seen an existing closed issue about that here : https://github.com/sgielen/picl-k3os-image-generator/issues/1

The `dmesg` command results with : 
```
[    6.941635] brcmfmac: F1 signature read @0x18000000=0x15264345
[    6.954731] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    6.955326] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43455-sdio.bin failed with error -2
```

First, I thought thath the problem was linked to k3os, but apparently K3OS is just an overlay on top on kernel/firmware as it said here : https://github.com/rancher/k3os/issues/345#issuecomment-603929615

It appears that broadcom firmware files are missing, I tried to update https://github.com/sgielen/picl-k3os-image-generator/blob/master/build-image.sh#L78 with last 1.20200212 rpi firmware but with no more luck.

@sgielen can you please help me to fix the probelm ?

Thanks

**Comment by sgielen** [comment]
I consider it mostly outside of the scope of this project but I'd be happy to help regardless.

First, you'll need the kernel module itself. Perhaps someone already published it somewhere for the armv8 kernel from the rpi firmware. I had to build a kernel module of my own recently, I'll share some of the steps and hopefully get you going a long way.

Since I had no cross compilation toolchain and didn't want to compile on the host, I started a Pod on the running k3s cluster:

```name=buildpod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: buildpod
spec:
  volumes:
  - name: modules
    hostPath:
      path: /lib/modules
  containers:
    - name: buildpod
      image: ubuntu:bionic
      stdin: true
      tty: true
      securityContext:
        privileged: true
      volumeMounts:
      - name: modules
        mountPath: /lib/modules
  nodeSelector:
    kubernetes.io/hostname: [the hostname of the node you want the kernel module for]
```

I ran this Pod and used `kubectl exec -ti buildpod bash` to get a shell inside it. Note that it's privileged and has read-write access to /lib/modules of the host.

First, I installed the necessary tools:

```
# apt-get update
# apt-get install -y git bc bison flex libssl-dev sudo wget python jq build-essential libncurses5-dev kmod
```

Then, downloaded the `rpi-source` tool which retrieves kernel sources for the exact kernel you're running currently.

```
# wget https://raw.githubusercontent.com/notro/rpi-source/master/rpi-source -O rpi-source
# chmod +x rpi-source
# ./rpi-source -q --tag-update

# mkdir -p $(dirname /usr/share/doc/raspberrypi-bootloader/changelog.Debian.gz)
# FIRMWAREVER=1.20190925
# COMMIT=$(wget -qO- https://api.github.com/repos/raspberrypi/firmware/commits/$FIRMWAREVER | jq -r '.sha')
# echo "firmware as of $COMMIT" | gzip -c > /usr/share/doc/raspberrypi-bootloader/changelog.Debian.gz
```
 I had to trick the tool into finding the right kernel sources:

# processor type is BCM2711 but the script assumes we run arm32, while we ran arm64 instead
      # this fixes the download of the correct Symvers file
      # perl -pi -e \
      #   's/def processor_type_suffix\(\):/def processor_type_suffix(): return "8"\ndef old_processor_type_suffix():/' \
      #   rpi-source

**Comment by sgielen** [comment]
Closing, since it's otherwise out of scope. If you would like to propose changes to the project to better allow this, do feel free to reopen :)

**Comment by Neonox31** [comment]
Thanks for your answer !

I'm not sure to understand well all you said but finally I found a solution.
I will create a PR with changes and let you decide if it is a suitable solution.

**Comment by Neonox31** [comment]
Here is the P.R : https://github.com/sgielen/picl-k3os-image-generator/pull/9
